from PyQt5 import QtCore, QtGui, QtWidgets
# import Common


class Ui_GrapWindow(object):
    def setupUi(self, GrapWindow):
        GrapWindow.setObjectName("GrapWindow")
        GrapWindow.resize(1105, 857)

        self.centralwidget = QtWidgets.QWidget(GrapWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")

#------------------------------vector selection groupbox--------------------------------------------------------------#

        self.groupBoxVectorSelection = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxVectorSelection.sizePolicy().hasHeightForWidth())
        self.groupBoxVectorSelection.setSizePolicy(sizePolicy)
        self.groupBoxVectorSelection.setObjectName("groupBoxVectorSelection")

        self.formLayoutVector = QtWidgets.QHBoxLayout(self.groupBoxVectorSelection)
        self.formLayoutVector.setObjectName("formLayoutVector")

        self.labelVector = QtWidgets.QLabel(self.groupBoxVectorSelection)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelVector.sizePolicy().hasHeightForWidth())
        self.labelVector.setSizePolicy(sizePolicy)
        self.labelVector.setObjectName("labelVector")
        self.formLayoutVector.addWidget(self.labelVector)

        self.comboBoxVector = QtWidgets.QComboBox(self.groupBoxVectorSelection)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxVector.sizePolicy().hasHeightForWidth())
        self.comboBoxVector.setSizePolicy(sizePolicy)
        self.comboBoxVector.setMinimumSize(QtCore.QSize(116, 0))
        self.comboBoxVector.setMaximumSize(QtCore.QSize(69, 16777215))
        self.comboBoxVector.setObjectName("comboBoxVector")
        self.comboBoxVector.addItem("")
        self.comboBoxVector.addItem("")
        self.comboBoxVector.addItem("")
        self.comboBoxVector.addItem("")
        self.formLayoutVector.addWidget(self.comboBoxVector)

        self.labelVectorDesc = QtWidgets.QLabel(self.groupBoxVectorSelection)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelVectorDesc.sizePolicy().hasHeightForWidth())
        self.labelVectorDesc.setSizePolicy(sizePolicy)
        self.labelVectorDesc.setObjectName("labelVectorDesc")
        self.formLayoutVector.addWidget(self.labelVectorDesc)

        self.lineEditVectorDesc = QtWidgets.QLineEdit(self.groupBoxVectorSelection)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditVectorDesc.sizePolicy().hasHeightForWidth())
        self.lineEditVectorDesc.setSizePolicy(sizePolicy)
        self.lineEditVectorDesc.setObjectName("lineEditVectorDesc")
        self.formLayoutVector.addWidget(self.lineEditVectorDesc)

        self.verticalLayout.addWidget(self.groupBoxVectorSelection)

#---------------------------------------graph view groupbox-----------------------------------------------------------#

        self.groupBoxGraphView = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxGraphView.sizePolicy().hasHeightForWidth())
        self.groupBoxGraphView.setSizePolicy(sizePolicy)
        self.groupBoxGraphView.setObjectName("groupBoxGraphView")

        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBoxGraphView)
        self.horizontalLayout.setObjectName("horizontalLayout")

        self.groupBoxGraphBuilder = QtWidgets.QGroupBox(self.groupBoxGraphView)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxGraphBuilder.sizePolicy().hasHeightForWidth())
        self.groupBoxGraphBuilder.setSizePolicy(sizePolicy)
        self.groupBoxGraphBuilder.setObjectName("groupBoxGraphBuilder")

        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBoxGraphBuilder)
        self.gridLayout_2.setObjectName("gridLayout_2")

        self.pushButtonZoomIn = QtWidgets.QPushButton(self.groupBoxGraphBuilder)
        self.pushButtonZoomIn.setObjectName("pushButtonZoomIn")
        self.gridLayout_2.addWidget(self.pushButtonZoomIn, 4, 0, 1, 1)

        self.pushButtonZoomOut = QtWidgets.QPushButton(self.groupBoxGraphBuilder)
        self.pushButtonZoomOut.setObjectName("pushButtonZoomOut")
        self.gridLayout_2.addWidget(self.pushButtonZoomOut, 4, 1, 1, 1)

        self.pushButtonEditRelationship = QtWidgets.QPushButton(self.groupBoxGraphBuilder)
        self.pushButtonEditRelationship.setObjectName("pushButtonEditRelationship")
        self.gridLayout_2.addWidget(self.pushButtonEditRelationship, 2, 1, 1, 1)

        self.pushButtonEditNode = QtWidgets.QPushButton(self.groupBoxGraphBuilder)
        self.pushButtonEditNode.setObjectName("pushButtonEditNode")
        self.gridLayout_2.addWidget(self.pushButtonEditNode, 2, 0, 1, 1)

        self.pushButtonDeleteRelationship = QtWidgets.QPushButton(self.groupBoxGraphBuilder)
        self.pushButtonDeleteRelationship.setObjectName("pushButtonDeleteRelationship")
        self.gridLayout_2.addWidget(self.pushButtonDeleteRelationship, 3, 1, 1, 1)

        self.comboBoxFormat = QtWidgets.QComboBox(self.groupBoxGraphBuilder)
        self.comboBoxFormat.setObjectName("comboBoxFormat")
        self.comboBoxFormat.addItem("")
        self.comboBoxFormat.addItem("")
        self.comboBoxFormat.addItem("")
        self.gridLayout_2.addWidget(self.comboBoxFormat, 0, 0, 1, 1)

        self.pushButtonAddNode = QtWidgets.QPushButton(self.groupBoxGraphBuilder)
        self.pushButtonAddNode.setObjectName("pushButtonAddNode")
        self.gridLayout_2.addWidget(self.pushButtonAddNode, 1, 0, 1, 1)

        self.pushButtonDeleteNode = QtWidgets.QPushButton(self.groupBoxGraphBuilder)
        self.pushButtonDeleteNode.setObjectName("pushButtonDeleteNode")
        self.gridLayout_2.addWidget(self.pushButtonDeleteNode, 3, 0, 1, 1)

        self.pushButtonExport = QtWidgets.QPushButton(self.groupBoxGraphBuilder)
        self.pushButtonExport.setObjectName("pushButtonExport")
        self.gridLayout_2.addWidget(self.pushButtonExport, 0, 1, 1, 1)

        self.pushButtonAddRelationship = QtWidgets.QPushButton(self.groupBoxGraphBuilder)
        self.pushButtonAddRelationship.setObjectName("pushButtonAddRelationship")
        self.gridLayout_2.addWidget(self.pushButtonAddRelationship, 1, 1, 1, 1)

        self.labelInterval = QtWidgets.QLabel(self.groupBoxGraphBuilder)
        self.labelInterval.setObjectName("labelInterval")
        self.gridLayout_2.addWidget(self.labelInterval, 6, 0, 1, 1)

        self.comboBoxIntervalUnits = QtWidgets.QComboBox(self.groupBoxGraphBuilder)
        self.comboBoxIntervalUnits.setObjectName("comboBoxIntervalUnits")
        self.comboBoxIntervalUnits.addItem("")
        self.gridLayout_2.addWidget(self.comboBoxIntervalUnits, 6, 1, 1, 1)

        self.comboBoxOrientation = QtWidgets.QComboBox(self.groupBoxGraphBuilder)
        self.comboBoxOrientation.setObjectName("comboBoxOrientation")
        self.comboBoxOrientation.addItem("")
        self.comboBoxOrientation.addItem("")
        self.comboBoxOrientation.addItem("")
        self.gridLayout_2.addWidget(self.comboBoxOrientation, 5, 1, 1, 1)

        self.labelTimelineOrientation = QtWidgets.QLabel(self.groupBoxGraphBuilder)
        self.labelTimelineOrientation.setObjectName("labelTimelineOrientation")
        self.gridLayout_2.addWidget(self.labelTimelineOrientation, 5, 0, 1, 1)

        self.horizontalLayout.addWidget(self.groupBoxGraphBuilder)

        self.graphicsView = QtWidgets.QGraphicsView(self.groupBoxGraphView)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView.sizePolicy().hasHeightForWidth())
        self.graphicsView.setSizePolicy(sizePolicy)
        self.graphicsView.setObjectName("graphicsView")
        self.horizontalLayout.addWidget(self.graphicsView)

        self.verticalLayout.addWidget(self.groupBoxGraphView)

#---------------------------------------------tabular view groupbox---------------------------------------------------#

        self.groupBoxTabularView = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxTabularView.setObjectName("groupBoxTabularView")

        self.gridLayout = QtWidgets.QGridLayout(self.groupBoxTabularView)
        self.gridLayout.setObjectName("gridLayout")

        self.labelNodeTable = QtWidgets.QLabel(self.groupBoxTabularView)
        self.labelNodeTable.setObjectName("labelNodeTable")
        self.gridLayout.addWidget(self.labelNodeTable, 0, 0, 1, 1)

        self.groupBoxIcons = QtWidgets.QGroupBox(self.groupBoxTabularView)
        self.groupBoxIcons.setObjectName("groupBoxIcons")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBoxIcons)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")

        self.tableWidgetIcons = QtWidgets.QTableWidget(self.groupBoxIcons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidgetIcons.sizePolicy().hasHeightForWidth())
        self.tableWidgetIcons.setSizePolicy(sizePolicy)
        self.tableWidgetIcons.setAlternatingRowColors(True)
        self.tableWidgetIcons.setShowGrid(False)
        self.tableWidgetIcons.setObjectName("tableWidgetIcons")
        self.tableWidgetIcons.setColumnCount(3)
        self.tableWidgetIcons.setRowCount(8)

        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetIcons.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetIcons.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetIcons.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetIcons.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetIcons.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetIcons.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetIcons.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetIcons.setVerticalHeaderItem(7, item)

        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetIcons.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetIcons.setHorizontalHeaderItem(1, item)

        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetIcons.setHorizontalHeaderItem(2, item)
        self.tableWidgetIcons.horizontalHeader().setStretchLastSection(True)
        self.tableWidgetIcons.verticalHeader().setStretchLastSection(False)
        self.horizontalLayout_2.addWidget(self.tableWidgetIcons)

        self.frameIconTableButtons = QtWidgets.QFrame(self.groupBoxIcons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameIconTableButtons.sizePolicy().hasHeightForWidth())
        self.frameIconTableButtons.setSizePolicy(sizePolicy)
        self.frameIconTableButtons.setMaximumSize(QtCore.QSize(110, 16777215))
        self.frameIconTableButtons.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameIconTableButtons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameIconTableButtons.setLineWidth(0)
        self.frameIconTableButtons.setObjectName("frameIconTableButtons")

        self.gridLayout_3 = QtWidgets.QGridLayout(self.frameIconTableButtons)
        self.gridLayout_3.setObjectName("gridLayout_3")

        self.pushButtonAddIcon = QtWidgets.QPushButton(self.frameIconTableButtons)
        self.pushButtonAddIcon.setObjectName("pushButtonAddIcon")
        self.gridLayout_3.addWidget(self.pushButtonAddIcon, 0, 0, 1, 1)

        self.pushButtonEditIcon = QtWidgets.QPushButton(self.frameIconTableButtons)
        self.pushButtonEditIcon.setObjectName("pushButtonEditIcon")
        self.gridLayout_3.addWidget(self.pushButtonEditIcon, 1, 0, 1, 1)

        self.pushButtonDeleteIcon = QtWidgets.QPushButton(self.frameIconTableButtons)
        self.pushButtonDeleteIcon.setObjectName("pushButtonDeleteIcon")
        self.gridLayout_3.addWidget(self.pushButtonDeleteIcon, 2, 0, 1, 1)

        self.horizontalLayout_2.addWidget(self.frameIconTableButtons)

        self.gridLayout.addWidget(self.groupBoxIcons, 4, 1, 3, 1)

        #creating nodes table
        self.tableWidgetNodes = QtWidgets.QTableWidget(self.groupBoxTabularView)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidgetNodes.sizePolicy().hasHeightForWidth())
        self.tableWidgetNodes.setSizePolicy(sizePolicy)
        self.tableWidgetNodes.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tableWidgetNodes.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tableWidgetNodes.setAlternatingRowColors(True)
        self.tableWidgetNodes.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.tableWidgetNodes.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.tableWidgetNodes.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidgetNodes.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidgetNodes.setShowGrid(False)
        self.tableWidgetNodes.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidgetNodes.setCornerButtonEnabled(False)
        self.tableWidgetNodes.setObjectName("tableWidgetNodes")
        self.tableWidgetNodes.setColumnCount(9)
        self.tableWidgetNodes.setRowCount(13)

        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetNodes.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetNodes.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetNodes.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetNodes.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetNodes.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetNodes.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetNodes.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetNodes.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetNodes.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetNodes.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetNodes.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetNodes.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetNodes.setVerticalHeaderItem(12, item)

        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetNodes.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetNodes.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetNodes.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetNodes.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetNodes.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetNodes.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetNodes.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetNodes.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetNodes.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidgetNodes.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item.setCheckState(QtCore.Qt.Unchecked)
        self.tableWidgetNodes.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item.setCheckState(QtCore.Qt.Unchecked)
        self.tableWidgetNodes.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item.setCheckState(QtCore.Qt.Unchecked)
        self.tableWidgetNodes.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item.setCheckState(QtCore.Qt.Unchecked)
        self.tableWidgetNodes.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item.setCheckState(QtCore.Qt.Unchecked)
        self.tableWidgetNodes.setItem(0, 5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item.setCheckState(QtCore.Qt.Unchecked)
        self.tableWidgetNodes.setItem(0, 6, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item.setCheckState(QtCore.Qt.Unchecked)
        self.tableWidgetNodes.setItem(0, 7, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidgetNodes.setItem(0, 8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetNodes.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item.setCheckState(QtCore.Qt.Unchecked)
        self.tableWidgetNodes.setItem(1, 8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetNodes.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item.setCheckState(QtCore.Qt.Unchecked)
        self.tableWidgetNodes.setItem(2, 8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetNodes.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item.setCheckState(QtCore.Qt.Unchecked)
        self.tableWidgetNodes.setItem(3, 8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetNodes.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item.setCheckState(QtCore.Qt.Unchecked)
        self.tableWidgetNodes.setItem(4, 8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetNodes.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item.setCheckState(QtCore.Qt.Unchecked)
        self.tableWidgetNodes.setItem(5, 8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetNodes.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetNodes.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetNodes.setItem(8, 0, item)

        self.tableWidgetNodes.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidgetNodes.horizontalHeader().setDefaultSectionSize(142)
        self.tableWidgetNodes.horizontalHeader().setSortIndicatorShown(True)
        self.tableWidgetNodes.horizontalHeader().setStretchLastSection(True)

        self.tableWidgetNodes.verticalHeader().setVisible(True)
        self.tableWidgetNodes.verticalHeader().setMinimumSectionSize(30)
        self.tableWidgetNodes.verticalHeader().setSortIndicatorShown(False)
        self.tableWidgetNodes.verticalHeader().setStretchLastSection(False)

        self.gridLayout.addWidget(self.tableWidgetNodes, 1, 0, 1, 2)

        #relationships groupbox
        self.groupBoxRelationships = QtWidgets.QGroupBox(self.groupBoxTabularView)
        self.groupBoxRelationships.setObjectName("groupBoxRelationships")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBoxRelationships)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.tableWidgetRelationships = QtWidgets.QTableWidget(self.groupBoxRelationships)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidgetRelationships.sizePolicy().hasHeightForWidth())
        self.tableWidgetRelationships.setSizePolicy(sizePolicy)
        self.tableWidgetRelationships.setAlternatingRowColors(True)
        self.tableWidgetRelationships.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidgetRelationships.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidgetRelationships.setShowGrid(False)
        self.tableWidgetRelationships.setObjectName("tableWidgetRelationships")
        self.tableWidgetRelationships.setColumnCount(5)
        self.tableWidgetRelationships.setRowCount(10)

        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetRelationships.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetRelationships.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetRelationships.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetRelationships.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetRelationships.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetRelationships.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetRelationships.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetRelationships.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetRelationships.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetRelationships.setVerticalHeaderItem(9, item)

        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetRelationships.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetRelationships.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetRelationships.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetRelationships.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetRelationships.setHorizontalHeaderItem(4, item)

        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item.setCheckState(QtCore.Qt.Unchecked)
        self.tableWidgetRelationships.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item.setCheckState(QtCore.Qt.Unchecked)
        self.tableWidgetRelationships.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item.setCheckState(QtCore.Qt.Unchecked)
        self.tableWidgetRelationships.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.tableWidgetRelationships.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item.setCheckState(QtCore.Qt.Unchecked)
        self.tableWidgetRelationships.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item.setCheckState(QtCore.Qt.Unchecked)
        self.tableWidgetRelationships.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item.setCheckState(QtCore.Qt.Unchecked)
        self.tableWidgetRelationships.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item.setCheckState(QtCore.Qt.Unchecked)
        self.tableWidgetRelationships.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item.setCheckState(QtCore.Qt.Unchecked)
        self.tableWidgetRelationships.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item.setCheckState(QtCore.Qt.Unchecked)
        self.tableWidgetRelationships.setItem(9, 0, item)
        self.tableWidgetRelationships.horizontalHeader().setStretchLastSection(True)
        self.horizontalLayout_3.addWidget(self.tableWidgetRelationships)
        self.gridLayout.addWidget(self.groupBoxRelationships, 4, 0, 3, 1)

        self.verticalLayout.addWidget(self.groupBoxTabularView)

        GrapWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(GrapWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1105, 21))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        GrapWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(GrapWindow)
        self.statusbar.setObjectName("statusbar")
        GrapWindow.setStatusBar(self.statusbar)
        self.actionEvent_Configurations = QtWidgets.QAction(GrapWindow)
        self.actionEvent_Configurations.setObjectName("actionEvent_Configurations")
        self.actionManage_Graph = QtWidgets.QAction(GrapWindow)
        self.actionManage_Graph.setObjectName("actionManage_Graph")
        self.actionSerach_Filter_Log_Entries = QtWidgets.QAction(GrapWindow)
        self.actionSerach_Filter_Log_Entries.setObjectName("actionSerach_Filter_Log_Entries")
        self.actionEnforcement_Action_Report = QtWidgets.QAction(GrapWindow)
        self.actionEnforcement_Action_Report.setObjectName("actionEnforcement_Action_Report")
        self.menuMenu.addAction(self.actionEvent_Configurations)
        self.menuMenu.addAction(self.actionSerach_Filter_Log_Entries)
        self.menuMenu.addAction(self.actionEnforcement_Action_Report)
        self.menuMenu.addAction(self.actionManage_Graph)
        self.menubar.addAction(self.menuMenu.menuAction())

        # self.menubar = Common.PickMenuBar(GrapWindow, omit=Common.GRAPH)
        # GrapWindow.setMenuBar(self.menubar)

        self.retranslateUi(GrapWindow)
        QtCore.QMetaObject.connectSlotsByName(GrapWindow)

    def retranslateUi(self, GrapWindow):
        _translate = QtCore.QCoreApplication.translate
        GrapWindow.setWindowTitle(_translate("GrapWindow", "Graph/Table View"))

        #filling in the vector selection group box
        self.groupBoxVectorSelection.setTitle(_translate("GrapWindow", "Vector Selection"))
        self.labelVector.setText(_translate("GrapWindow", "Vector:"))
        self.comboBoxVector.setItemText(0, _translate("GrapWindow", "Selec A Vector"))
        self.comboBoxVector.setItemText(1, _translate("GrapWindow", "Vector A"))
        self.comboBoxVector.setItemText(2, _translate("GrapWindow", "Vector B"))
        self.comboBoxVector.setItemText(3, _translate("GrapWindow", "Vector C"))
        self.labelVectorDesc.setText(_translate("GrapWindow", "Vector Description"))

        #filling in the graph view group box
        self.groupBoxGraphView.setTitle(_translate("GrapWindow", "Graphical View"))
        self.groupBoxGraphBuilder.setTitle(_translate("GrapWindow", "Graph Builder"))
        self.pushButtonZoomIn.setText(_translate("GrapWindow", "Zoom In"))
        self.pushButtonZoomOut.setText(_translate("GrapWindow", "Zoom Out"))
        self.pushButtonEditRelationship.setText(_translate("GrapWindow", "Edit Relationship"))
        self.pushButtonEditNode.setText(_translate("GrapWindow", "Edit Node"))
        self.pushButtonDeleteRelationship.setText(_translate("GrapWindow", "Delete Relationship"))
        self.comboBoxFormat.setItemText(0, _translate("GrapWindow", "Export As"))
        self.comboBoxFormat.setItemText(1, _translate("GrapWindow", "JPEG"))
        self.comboBoxFormat.setItemText(2, _translate("GrapWindow", "PNG"))
        self.pushButtonAddNode.setText(_translate("GrapWindow", "Add Node"))
        self.pushButtonDeleteNode.setText(_translate("GrapWindow", "Delete Node"))
        self.pushButtonExport.setText(_translate("GrapWindow", "Export"))
        self.pushButtonAddRelationship.setText(_translate("GrapWindow", "Add Relationship"))
        self.labelInterval.setText(_translate("GrapWindow", "Interval:"))
        self.comboBoxIntervalUnits.setItemText(0, _translate("GrapWindow", "Interval Units"))
        self.comboBoxOrientation.setItemText(0, _translate("GrapWindow", "Select Orientation"))
        self.comboBoxOrientation.setItemText(1, _translate("GrapWindow", "Vertical"))
        self.comboBoxOrientation.setItemText(2, _translate("GrapWindow", "Horizontal"))
        self.labelTimelineOrientation.setText(_translate("GrapWindow", "Timeline Orientation:"))

        #filling in the tabular view group box
        self.groupBoxTabularView.setTitle(_translate("GrapWindow", "Tabular View"))
        self.labelNodeTable.setText(_translate("GrapWindow", "Node Table"))
        self.groupBoxIcons.setTitle(_translate("GrapWindow", "Icon Table"))
        item = self.tableWidgetIcons.horizontalHeaderItem(0)
        item.setText(_translate("GrapWindow", "Icon Name"))
        item = self.tableWidgetIcons.horizontalHeaderItem(1)
        item.setText(_translate("GrapWindow", "Icon Source"))
        item = self.tableWidgetIcons.horizontalHeaderItem(2)
        item.setText(_translate("GrapWindow", "Image Preview"))
        self.pushButtonAddIcon.setText(_translate("GrapWindow", "Add Icon"))
        self.pushButtonEditIcon.setText(_translate("GrapWindow", "Edit Icon"))
        self.pushButtonDeleteIcon.setText(_translate("GrapWindow", "Delete Icon"))
        self.tableWidgetNodes.setSortingEnabled(True)
        item = self.tableWidgetNodes.verticalHeaderItem(0)
        item.setText(_translate("GrapWindow", "Node Property Visibility"))
        item = self.tableWidgetNodes.horizontalHeaderItem(0)
        item.setText(_translate("GrapWindow", "Node Id"))
        item = self.tableWidgetNodes.horizontalHeaderItem(1)
        item.setText(_translate("GrapWindow", "Node Name"))
        item = self.tableWidgetNodes.horizontalHeaderItem(2)
        item.setText(_translate("GrapWindow", "Node Timestamp"))
        item = self.tableWidgetNodes.horizontalHeaderItem(3)
        item.setText(_translate("GrapWindow", "Node Description"))
        item = self.tableWidgetNodes.horizontalHeaderItem(4)
        item.setText(_translate("GrapWindow", "Log Entry Reference"))
        item = self.tableWidgetNodes.horizontalHeaderItem(5)
        item.setText(_translate("GrapWindow", "Log Creator"))
        item = self.tableWidgetNodes.horizontalHeaderItem(6)
        item.setText(_translate("GrapWindow", "Icon Type"))
        item = self.tableWidgetNodes.horizontalHeaderItem(7)
        item.setText(_translate("GrapWindow", "Source"))
        item = self.tableWidgetNodes.horizontalHeaderItem(8)
        item.setText(_translate("GrapWindow", "Node Visibility"))
        __sortingEnabled = self.tableWidgetNodes.isSortingEnabled()
        self.tableWidgetNodes.setSortingEnabled(False)
        item = self.tableWidgetNodes.item(1, 0)
        item.setText(_translate("GrapWindow", "0-001"))
        item = self.tableWidgetNodes.item(2, 0)
        item.setText(_translate("GrapWindow", "0-002"))
        item = self.tableWidgetNodes.item(3, 0)
        item.setText(_translate("GrapWindow", "0-003"))
        item = self.tableWidgetNodes.item(4, 0)
        item.setText(_translate("GrapWindow", "0-004"))
        item = self.tableWidgetNodes.item(5, 0)
        item.setText(_translate("GrapWindow", "0-005"))
        item = self.tableWidgetNodes.item(6, 0)
        item.setText(_translate("GrapWindow", "0-006"))
        item = self.tableWidgetNodes.item(7, 0)
        item.setText(_translate("GrapWindow", "0-007"))
        item = self.tableWidgetNodes.item(8, 0)
        item.setText(_translate("GrapWindow", "0-008"))
        self.tableWidgetNodes.setSortingEnabled(__sortingEnabled)
        self.groupBoxRelationships.setTitle(_translate("GrapWindow", "Relationship Table"))
        self.tableWidgetRelationships.setSortingEnabled(True)
        item = self.tableWidgetRelationships.horizontalHeaderItem(1)
        item.setText(_translate("GrapWindow", "Relationship ID"))
        item = self.tableWidgetRelationships.horizontalHeaderItem(2)
        item.setText(_translate("GrapWindow", "Parent"))
        item = self.tableWidgetRelationships.horizontalHeaderItem(3)
        item.setText(_translate("GrapWindow", "Child"))
        item = self.tableWidgetRelationships.horizontalHeaderItem(4)
        item.setText(_translate("GrapWindow", "Label"))
        __sortingEnabled = self.tableWidgetRelationships.isSortingEnabled()
        self.tableWidgetRelationships.setSortingEnabled(False)
        self.tableWidgetRelationships.setSortingEnabled(__sortingEnabled)
        self.menuMenu.setTitle(_translate("GrapWindow", "Menu"))
        self.actionEvent_Configurations.setText(_translate("GrapWindow", "Event Configurations"))
        self.actionManage_Graph.setText(_translate("GrapWindow", "Manage Graph"))
        self.actionSerach_Filter_Log_Entries.setText(_translate("GrapWindow", "Serach/Filter Log Entries"))
        self.actionEnforcement_Action_Report.setText(_translate("GrapWindow", "Enforcement Action Report"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    GrapWindow = QtWidgets.QMainWindow()
    ui = Ui_GrapWindow()
    ui.setupUi(GrapWindow)
    GrapWindow.show()
    sys.exit(app.exec_())
